# Generated by Django 3.2.24 on 2024-02-16 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_article'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='identifier',
            new_name='id',
        ),
    ]
